import { beforeEach,describe,expect,it,vi } from 'vitest';
import apiClient from './apiClient';
import * as fan from './fantasyService';
import * as admin from './fantasyAdminService';

vi.mock('./apiClient',()=>({default:{get:vi.fn(),post:vi.fn(),put:vi.fn(),patch:vi.fn()}}));
const client=vi.mocked(apiClient);
beforeEach(()=>{vi.clearAllMocks();client.get.mockResolvedValue({data:[]} as never);client.post.mockResolvedValue({data:{}} as never);client.put.mockResolvedValue({data:{}} as never);client.patch.mockResolvedValue({data:{}} as never);});

describe('Fantasy API services',()=>{
 it('uses genuine competition, player, team and lineup endpoints',async()=>{await fan.fetchFantasyCompetitions();await fan.fetchFantasyPlayers('c1');await fan.fetchMyTeams();await fan.createFantasyTeam({name:'XI',fantasy_competition:'c1',selections:[]});await fan.updateFantasyLineup('t1',[]);expect(client.get).toHaveBeenCalledWith('/fantasy/competitions/');expect(client.get).toHaveBeenCalledWith('/fantasy/players/',{params:{competition:'c1'}});expect(client.get).toHaveBeenCalledWith('/fantasy/teams/');expect(client.post).toHaveBeenCalledWith('/fantasy/teams/',expect.any(Object));expect(client.put).toHaveBeenCalledWith('/fantasy/teams/t1/lineup/',{selections:[]});});
 it('uses preview, transfer, balance, history and points endpoints',async()=>{await fan.previewFantasyTransfer('t1',{gameweek:'g1',player_out:'p1',player_in:'p2'});await fan.makeFantasyTransfer('t1',{gameweek:'g1',player_out:'p1',player_in:'p2'});await fan.fetchTransferBalance('t1','g1');await fan.fetchTransferHistory('t1');await fan.fetchTeamPoints('t1');expect(client.post).toHaveBeenCalledWith('/fantasy/teams/t1/transfer_preview/',expect.any(Object));expect(client.post).toHaveBeenCalledWith('/fantasy/teams/t1/transfer/',expect.any(Object));expect(client.get).toHaveBeenCalledWith('/fantasy/teams/t1/transfer_balance/',{params:{gameweek:'g1'}});expect(client.get).toHaveBeenCalledWith('/fantasy/teams/t1/transfers/');expect(client.get).toHaveBeenCalledWith('/fantasy/teams/t1/points/');});
 it('uses gameweek, leaderboard and selected-league endpoints',async()=>{await fan.fetchFantasyGameweeks('c1');await fan.fetchGameweekPoints('g1');await fan.fetchGameweekLeaderboard('g1');await fan.fetchCompetitionLeaderboard('c1');await fan.fetchMyLeagues();await fan.fetchPublicLeagues();await fan.fetchLeagueMembers('selected');await fan.fetchLeagueStandings('selected');expect(client.get).toHaveBeenCalledWith('/fantasy/leagues/selected/members/');expect(client.get).toHaveBeenCalledWith('/fantasy/leagues/selected/standings/');});
 it('covers create, join, code join and leave league mutations',async()=>{await fan.createFantasyLeague({fantasy_competition:'c1',name:'Friends',visibility:'PRIVATE'});await fan.joinFantasyLeague('l1');await fan.joinFantasyLeagueByCode('ABC');await fan.leaveFantasyLeague('l1');expect(client.post).toHaveBeenCalledWith('/fantasy/leagues/',expect.any(Object));expect(client.post).toHaveBeenCalledWith('/fantasy/leagues/l1/join/');expect(client.post).toHaveBeenCalledWith('/fantasy/leagues/join_by_code/',{code:'ABC'});expect(client.post).toHaveBeenCalledWith('/fantasy/leagues/l1/leave/');});
 it('covers all admin API groups',async()=>{await admin.fetchCanonicalFantasyOptions();await admin.adminCreateCompetition({name:'Fantasy'});await admin.adminUpdateCompetition('c1',{name:'Updated'});await admin.fetchFantasyPlayerCandidates('c1');await admin.adminCreatePlayer({fantasy_competition:'c1',player:'a1',position:'GK',price:5,eligible:true,availability:'AVAILABLE'});await admin.adminUpdatePlayer('p1',{price:6});await admin.adminCreateGameweek({fantasy_competition:'c1'});await admin.adminUpdateGameweek('g1',{fixtures:['f1']});await admin.fetchFantasyFixtureCandidates('c1');await admin.adminTransitionGameweek('g1','OPEN');await admin.adminRecalculateGameweek('g1');await admin.adminFinalizeGameweek('g1');await admin.fetchFantasyStatisticTypes('c1');await admin.adminCreateScoringRule({fantasy_competition:'c1',statistic_type:'GOAL',points:'5'});await admin.adminCreateCorrection({player_points:'pp1',new_value:'4',reason:'Verified correction'});await admin.fetchAdminCorrections('g1');await admin.fetchAdminLeagueOverview();expect(client.post).toHaveBeenCalledWith('/fantasy/admin/corrections/',expect.objectContaining({reason:'Verified correction'}));expect(client.get).toHaveBeenCalledWith('/fantasy/leagues/admin-overview/');});
 it('covers adminUpdateScoringRule and adminDeleteScoringRule',async()=>{client.patch.mockResolvedValue({data:{id:'sr1',statistic_type:'GOALS',points:'7.00',enabled:false,conditions:{},fantasy_competition:'c1'}} as never);client.delete=vi.fn().mockResolvedValue({data:{}} as never);await admin.adminUpdateScoringRule('sr1',{points:'7',enabled:false});await admin.adminDeleteScoringRule('sr1');expect(client.patch).toHaveBeenCalledWith('/fantasy/admin/scoring-rules/sr1/',{points:'7',enabled:false});expect(client.delete).toHaveBeenCalledWith('/fantasy/admin/scoring-rules/sr1/');});
});
