import { useEffect, useState } from 'react';
import { FiAlertTriangle, FiActivity, FiDownload } from 'react-icons/fi';
import AdminLayout from '../../../components/admin/AdminLayout';
import { useAuthStore } from '../../../store/authStore';
import {
  fetchRecentReports,
  generateReport,
  REPORT_CATEGORIES,
  type GeneratedReport,
} from '../../../services/reportsService';
import './ReportsPage.css';

function formatDateTime(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function ReportsPage() {
  const currentAdmin = useAuthStore((state) => state.user?.full_name || state.user?.email || 'You');
  const [reports, setReports] = useState<GeneratedReport[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [generatingId, setGeneratingId] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetchRecentReports()
      .then((result) => {
        if (!cancelled) setReports(result);
      })
      .catch(() => {
        if (!cancelled) setLoadError('Could not load reports. Please try again.');
      })
      .finally(() => {
        if (!cancelled) setIsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const handleGenerate = async (categoryId: string) => {
    setGeneratingId(categoryId);
    setActionError(null);
    try {
      const report = await generateReport(categoryId, currentAdmin);
      setReports((current) => [report, ...current]);
    } catch (error) {
      setActionError(error instanceof Error ? error.message : 'Could not generate this report.');
    } finally {
      setGeneratingId(null);
    }
  };

  return (
    <AdminLayout>
      <div className="rpt-root">
        <div className="rpt-head">
          <p className="rpt-eyebrow">Welcome back</p>
          <h1>Reports</h1>
          <p>Generate canned reports across trading, finance, users, markets, and system health.</p>
        </div>

        {(loadError || actionError) && (
          <div className="rpt-error-banner">
            <FiAlertTriangle aria-hidden="true" />
            <span>{loadError ?? actionError}</span>
          </div>
        )}

        <div className="rpt-category-grid">
          {REPORT_CATEGORIES.map((category) => (
            <div className="rpt-category-card" key={category.id}>
              <h3>{category.label}</h3>
              <p>{category.description}</p>
              <button
                type="button"
                className="rpt-btn rpt-btn--outline"
                disabled={generatingId === category.id}
                onClick={() => handleGenerate(category.id)}
              >
                <FiDownload /> {generatingId === category.id ? 'Generating…' : 'Export'}
              </button>
            </div>
          ))}
        </div>

        {isLoading ? (
          <div className="rpt-loading">
            <FiActivity aria-hidden="true" className="rpt-loading__icon" />
            Loading recent reports…
          </div>
        ) : (
          <div className="rpt-panel">
            <h2>Recent Reports</h2>
            <div className="rpt-table-scroll">
              <table className="rpt-table">
                <thead>
                  <tr>
                    <th>Category</th>
                    <th>Format</th>
                    <th>Generated By</th>
                    <th>Generated</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((report) => (
                    <tr key={report.id}>
                      <td>{report.categoryLabel}</td>
                      <td>{report.format}</td>
                      <td>{report.generatedBy}</td>
                      <td>{formatDateTime(report.generatedAt)}</td>
                    </tr>
                  ))}
                  {reports.length === 0 && (
                    <tr>
                      <td colSpan={4} className="rpt-table__empty">
                        No reports generated yet.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </AdminLayout>
  );
}

export default ReportsPage;
