import { useEffect, useMemo, useState } from 'react'; import { useNavigate, useParams } from 'react-router-dom'; import { FiArrowLeft } from 'react-icons/fi';
import Sidebar from '../../../components/fan/Sidebar'; import Topbar from '../sections/Topbar'; import Footer from '../../../components/landing/Footer'; import DashboardNotice from '../../../components/fan/dashboard/DashboardNotice';
import { fetchMarket, fetchMarketOrderBook, fetchMarketPriceHistory, type Market, type MarketOrderBook, type MarketPriceHistory, type OutcomeId } from '../../../services/fanMarketsServices'; import { backendQuantityToShares, formatMarketSharePrice, normalizedPriceToUgxSharePrice } from '../../../utils/marketPricing.ts';
import '../sections/FanDashboard.css'; import './Markets.css'; import './FanMarketDetail.css';
type Range='1H'|'6H'|'1D'|'1W'|'ALL';
function optionsFor(range:Range){const end=new Date();if(range==='ALL')return{interval:'DAY' as const,limit:365};const hours=range==='1H'?1:range==='6H'?6:range==='1D'?24:168;return{interval:range==='1W'?'HOUR' as const:'RAW' as const,start:new Date(end.getTime()-hours*3600000).toISOString(),end:end.toISOString(),limit:1000};}
function MarketDetailChart(){const navigate=useNavigate();const{marketId}=useParams<{marketId:string}>();const[sidebar,setSidebar]=useState(false);const[market,setMarket]=useState<Market|null>(null);const[outcomeId,setOutcomeId]=useState<OutcomeId>('YES');const[range,setRange]=useState<Range>('1D');const[history,setHistory]=useState<MarketPriceHistory|null>(null);const[book,setBook]=useState<MarketOrderBook|null>(null);const[error,setError]=useState('');
 useEffect(()=>{if(!marketId)return;fetchMarket(marketId).then(setMarket).catch(()=>setError("Couldn't load this market."));},[marketId]);const outcome=market?.outcomes.find((item)=>item.id===outcomeId);
 useEffect(()=>{if(!market||!outcome)return;let cancelled=false;Promise.all([fetchMarketPriceHistory(market.id,outcome.backendOutcomeId,optionsFor(range)),fetchMarketOrderBook(market.id,outcome.backendOutcomeId)]).then(([h,b])=>{if(!cancelled){setHistory(h);setBook(b);}}).catch((e)=>{if(!cancelled)setError(e instanceof Error?e.message:'Could not load trading data.');});return()=>{cancelled=true;};},[market,outcome,range]);
 const points=useMemo(()=>history?.points.map((point)=>{const raw='price'in point?point.price:point.close;return normalizedPriceToUgxSharePrice(Number(raw));})??[],[history]); const max=Math.max(...points,1); const min=Math.min(...points,0); const poly=points.map((p,i)=>`${points.length===1?50:(i/(points.length-1))*100},${100-((p-min)/(max-min||1))*100}`).join(' ');
 return <div className="fan-dashboard"><Sidebar isOpen={sidebar} onClose={()=>setSidebar(false)}/><div className="fan-dashboard-main"><Topbar onMenuClick={()=>setSidebar(true)}/><div className="fan-dashboard-content market-detail-page"><button type="button" className="market-back-btn" onClick={()=>navigate(marketId?`/fan/markets/${marketId}`:'/fan/markets')}><FiArrowLeft/> Back</button><section className="dashboard-card market-detail-card"><h3 className="market-details-question">{market?.question??'Market'}</h3>{error&&<DashboardNotice tone="error" title="Trading data unavailable" message={error}/>}<div className="trade-tabs">{market?.outcomes.map((o)=><button type="button" key={o.id} className={o.id===outcomeId?'active':''} onClick={()=>setOutcomeId(o.id)}>{o.label}</button>)}</div><div className="price-history-range-tabs">{(['1H','6H','1D','1W','ALL'] as Range[]).map((r)=><button type="button" key={r} className={r===range?'active':''} onClick={()=>setRange(r)}>{r}</button>)}</div>
 {history&&points.length===0?<DashboardNotice tone="empty" title="No trades yet" message="No executed trades exist for this outcome in the selected range."/>:points.length>0?<svg role="img" aria-label="Genuine price history" viewBox="0 0 100 100" className="price-history-sparkline"><polyline fill="none" stroke="currentColor" strokeWidth="2" points={poly}/></svg>:<p>Loading price history…</p>}
 <h3>Order Book</h3>{book&&book.bids.length===0&&book.asks.length===0?<DashboardNotice tone="empty" title="No orders yet" message="There are no open orders for this outcome."/>:book?<><p>Best bid: {book.best_bid===null?'No buy liquidity':formatMarketSharePrice(normalizedPriceToUgxSharePrice(Number(book.best_bid)))} · Best ask: {book.best_ask===null?'No sell liquidity':formatMarketSharePrice(normalizedPriceToUgxSharePrice(Number(book.best_ask)))}</p><div className="pmd-orderbook-grid"><div><h4>Bids</h4>{book.bids.map((l)=><div key={`b-${l.price}`}><span>{formatMarketSharePrice(normalizedPriceToUgxSharePrice(Number(l.price)))}</span> <span>{backendQuantityToShares(Number(l.quantity)).toFixed(4)} shares ({l.order_count})</span></div>)}</div><div><h4>Asks</h4>{book.asks.map((l)=><div key={`a-${l.price}`}><span>{formatMarketSharePrice(normalizedPriceToUgxSharePrice(Number(l.price)))}</span> <span>{backendQuantityToShares(Number(l.quantity)).toFixed(4)} shares ({l.order_count})</span></div>)}</div></div></>:<p>Loading order book…</p>}</section></div><Footer/></div></div>;
}
export default MarketDetailChart;
