import { useEffect, useState } from 'react';
import type { Competition, FantasyTeam } from '../types';
import type { FantasyLeague, FantasyLeagueMember, FantasyStanding } from '../../../../services/fantasyService';
import { createFantasyLeague, fetchCompetitionLeaderboard, fetchLeagueMembers, fetchLeagueStandings, fetchMyLeagues, fetchPublicLeagues, joinFantasyLeague, joinFantasyLeagueByCode, leaveFantasyLeague } from '../../../../services/fantasyService';
import { Modal, Drawer } from './Modal';

interface Props{competition:Competition;team:FantasyTeam}
export default function Leagues({competition}:Props){
 const [tab,setTab]=useState<'mine'|'public'|'overall'>('mine'); const [mine,setMine]=useState<FantasyLeague[]>([]); const [publicRows,setPublic]=useState<FantasyLeague[]>([]); const [overall,setOverall]=useState<FantasyStanding[]>([]);
 const [selected,setSelected]=useState<FantasyLeague|null>(null); const [members,setMembers]=useState<FantasyLeagueMember[]>([]); const [standings,setStandings]=useState<FantasyStanding[]>([]); const [createOpen,setCreateOpen]=useState(false); const [joinOpen,setJoinOpen]=useState(false); const [name,setName]=useState(''); const [visibility,setVisibility]=useState<'PUBLIC'|'PRIVATE'>('PRIVATE'); const [code,setCode]=useState(''); const [error,setError]=useState('');
 async function reload(){const [m,p,o]=await Promise.all([fetchMyLeagues(),fetchPublicLeagues(),fetchCompetitionLeaderboard(competition.id)]);setMine(m.filter(x=>x.fantasy_competition===competition.id));setPublic(p.filter(x=>x.fantasy_competition===competition.id));setOverall(o);}
 // Reload when the selected competition changes; the backend is authoritative.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{void reload().catch(e=>setError(e instanceof Error?e.message:'Could not load leagues.'));},[competition.id]);
 async function open(row:FantasyLeague){setSelected(row);setError('');try{const [m,s]=await Promise.all([fetchLeagueMembers(row.id),fetchLeagueStandings(row.id)]);setMembers(m);setStandings(s);}catch(e){setError(e instanceof Error?e.message:'Could not load this league.');}}
 async function create(){try{const row=await createFantasyLeague({fantasy_competition:competition.id,name,visibility});setCreateOpen(false);setName('');await reload();await open(row);}catch(e){setError(e instanceof Error?e.message:'Could not create league.');}}
 async function joinCode(){try{const row=await joinFantasyLeagueByCode(code.trim().toUpperCase());setJoinOpen(false);setCode('');await reload();await open(row);}catch(e){setError(e instanceof Error?e.message:'Invite code not recognised.');}}
 async function join(row:FantasyLeague){try{await joinFantasyLeague(row.id);await reload();await open(row);}catch(e){setError(e instanceof Error?e.message:'Could not join league.');}}
 async function leave(){if(!selected)return;try{await leaveFantasyLeague(selected.id);setSelected(null);await reload();}catch(e){setError(e instanceof Error?e.message:'Could not leave league.');}}
 const rows=tab==='mine'?mine:publicRows;
 return <div className="leagues"><div className="leagues-tabs"><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>My Leagues</button><button className={tab==='public'?'active':''} onClick={()=>setTab('public')}>Public Leagues</button><button className={tab==='overall'?'active':''} onClick={()=>setTab('overall')}>Overall Leaderboard</button></div>{error&&<p className="transfer-cost-warning" role="alert">{error}</p>}
 {tab!=='overall'?<><div className="sb-summary-bar"><span>Compete with friends, clubs and the League OS community.</span><div className="sb-actions" style={{margin:0}}><button className="btn btn-secondary" onClick={()=>setJoinOpen(true)}>Join by code</button><button className="btn btn-primary" onClick={()=>setCreateOpen(true)}>Create league</button></div></div><div className="league-card-list">{rows.map(row=><div className="league-card" key={row.id}><button className="btn-link" onClick={()=>void open(row)}><strong>{row.name}</strong><span>{row.visibility} · {row.member_count} members</span></button>{tab==='public'&&!mine.some(x=>x.id===row.id)&&<button className="btn btn-secondary" onClick={()=>void join(row)}>Join</button>}</div>)}{!rows.length&&<div className="empty-state"><h3>No leagues found</h3></div>}</div></>:<table className="standings-table"><thead><tr><th>Rank</th><th>Team</th><th>Manager</th><th>Points</th></tr></thead><tbody>{overall.map(row=><tr key={row.team_id}><td>{row.rank}</td><td>{row.team__name??row.team_name}</td><td>{row.manager}</td><td>{row.total_points}</td></tr>)}</tbody></table>}
 {selected&&<Drawer title={selected.name} subtitle={`${selected.visibility} · ${selected.member_count} members`} onClose={()=>setSelected(null)}><h3>Standings</h3><table className="standings-table"><tbody>{standings.map(row=><tr key={row.team_id}><td>{row.rank}</td><td>{row.team__name??row.team_name}</td><td>{row.manager}</td><td>{row.total_points}</td></tr>)}</tbody></table><h3>Members</h3><ul className="rules-list">{members.map(row=><li key={row.team_id}><span>{row.fantasy_team} · {row.manager}</span><strong>{row.total_points}</strong></li>)}</ul>{selected.join_code&&<p>Invite code: <strong>{selected.join_code}</strong></p>}<button className="btn btn-danger" onClick={()=>void leave()}>Leave league</button></Drawer>}
 {createOpen&&<Modal title="Create league" onClose={()=>setCreateOpen(false)} footer={<button className="btn btn-primary" disabled={!name.trim()} onClick={()=>void create()}>Create league</button>}><label>League name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Visibility<select value={visibility} onChange={e=>setVisibility(e.target.value as 'PUBLIC'|'PRIVATE')}><option value="PRIVATE">Private</option><option value="PUBLIC">Public</option></select></label></Modal>}
 {joinOpen&&<Modal title="Join a private league" onClose={()=>setJoinOpen(false)} footer={<button className="btn btn-primary" disabled={!code.trim()} onClick={()=>void joinCode()}>Join league</button>}><label>Invite code<input value={code} onChange={e=>setCode(e.target.value)}/></label></Modal>}</div>;
}
