import { useState, useRef } from 'react';
import { FiGlobe, FiInstagram, FiTwitter, FiYoutube, FiLinkedin, FiDownload, FiSave, FiPlus, FiX, FiUpload, FiImage, FiTrash2 } from 'react-icons/fi';
import ClubAdminLayout from '../../../components/clubadmin/ClubAdminLayout';
import '../../../components/clubadmin/ClubAdminLayout.css';
import './ClubProfilePage.css';

const TABS = ['Profile', 'Venues', 'Media Assets'];
const PALETTE = ['#FFD700', '#1A1A1A', '#7C3AED', '#FFFFFF', '#22C55E'];

const RECENT_BRANDING: { text: string; time: string }[] = [];

type FormData = {
  clubName: string; email: string; phone: string; website: string;
  founded: string; nickname: string; ground: string; colours: string; bio: string;
};

const INIT_FORM: FormData = {
  clubName: '', email: '', phone: '', website: '',
  founded: '', nickname: '', ground: '', colours: '', bio: '',
};

type VenueType = 'Home' | 'Training' | 'Alternative';
type Venue = { id: string; name: string; address: string; capacity: string; type: VenueType; facilities: string };

type MediaAsset = { id: string; name: string; category: string; size: string; addedAt: string };
const MEDIA_CATEGORIES = ['Crest / Logo', 'Kit', 'Banner', 'Photo', 'Video', 'Document', 'Other'];

let seq = 10;
function nextId() { return `prof-${seq++}`; }

export default function ClubProfilePage() {
  const [activeTab, setActiveTab] = useState('Profile');

  // Profile tab
  const [form, setForm] = useState<FormData>(INIT_FORM);
  const [saved, setSaved] = useState<FormData>(INIT_FORM);
  const [dirty, setDirty] = useState(false);

  // Venues tab
  const [venues, setVenues] = useState<Venue[]>([]);
  const [showVenueModal, setShowVenueModal] = useState(false);
  const [venueForm, setVenueForm] = useState<Omit<Venue, 'id'>>({ name: '', address: '', capacity: '', type: 'Home', facilities: '' });

  // Media tab
  const [assets, setAssets] = useState<MediaAsset[]>([]);
  const [mediaCategory, setMediaCategory] = useState(MEDIA_CATEGORIES[0]);
  const fileRef = useRef<HTMLInputElement>(null);

  const [toast, setToast] = useState('');
  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 3000); };

  // Profile handlers
  const handleChange = (k: keyof FormData) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm(f => ({ ...f, [k]: e.target.value }));
    setDirty(true);
  };
  const saveChanges = () => { setSaved(form); setDirty(false); showToast('Club profile saved successfully'); };
  const discard = () => { setForm(saved); setDirty(false); showToast('Changes discarded'); };

  const downloadGuidelines = () => {
    const content = [
      `BRAND GUIDELINES — ${form.clubName}`, `Season 2025/26`,
      `Generated by League OS · ${new Date().toLocaleDateString()}`, ``,
      `CLUB IDENTITY`, `  Club Name:    ${form.clubName}`, `  Nickname:     ${form.nickname}`,
      `  Founded:      ${form.founded}`, `  Home Ground:  ${form.ground}`, `  Home Colours: ${form.colours}`, ``,
      `CONTACT & WEB`, `  Email:   ${form.email}`, `  Phone:   ${form.phone}`, `  Website: ${form.website}`, ``,
      `BRAND PALETTE`, `  ${PALETTE.join('  |  ')}`, ``, `CLUB BIO`, `  ${form.bio}`,
    ].join('\n');
    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([content], { type: 'text/plain' })),
      download: `${(form.clubName || 'club').replace(/\s+/g, '_')}_brand_guidelines.txt`,
    });
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    showToast('Brand guidelines downloaded');
  };

  // Venue handlers
  const openVenueModal = () => { setVenueForm({ name: '', address: '', capacity: '', type: 'Home', facilities: '' }); setShowVenueModal(true); };
  const saveVenue = () => {
    if (!venueForm.name.trim()) return;
    setVenues(prev => [...prev, { id: nextId(), ...venueForm }]);
    setShowVenueModal(false);
    showToast(`${venueForm.name} added`);
  };
  const removeVenue = (id: string) => { setVenues(prev => prev.filter(v => v.id !== id)); showToast('Venue removed'); };

  // Media handlers
  const handleFilePick = (files: FileList | null) => {
    if (!files) return;
    const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
    const newAssets: MediaAsset[] = Array.from(files).map(f => ({
      id: nextId(), name: f.name, category: mediaCategory,
      size: f.size > 1_048_576 ? `${(f.size / 1_048_576).toFixed(1)} MB` : `${Math.round(f.size / 1024)} KB`,
      addedAt: today,
    }));
    setAssets(prev => [...prev, ...newAssets]);
    showToast(`${newAssets.length} file${newAssets.length > 1 ? 's' : ''} uploaded`);
  };
  const removeAsset = (id: string) => { setAssets(prev => prev.filter(a => a.id !== id)); showToast('Asset removed'); };

  const FIELDS: { label: string; key: keyof FormData; type?: string }[] = [
    { label: 'Club Name', key: 'clubName' }, { label: 'Official Email', key: 'email', type: 'email' },
    { label: 'Phone Number', key: 'phone', type: 'tel' }, { label: 'Website', key: 'website' },
    { label: 'Founded', key: 'founded' }, { label: 'Nickname', key: 'nickname' },
    { label: 'Home Ground', key: 'ground' }, { label: 'Home Colours', key: 'colours' },
  ];

  return (
    <ClubAdminLayout>
      {toast && <div className="ca-toast">{toast}</div>}

      {/* Venue modal */}
      {showVenueModal && (
        <div className="ca-modal-overlay" onClick={() => setShowVenueModal(false)}>
          <div className="ca-modal" onClick={e => e.stopPropagation()}>
            <div className="ca-modal-header">
              <h2 className="ca-modal-title">Add Venue</h2>
              <button type="button" className="ca-modal-close" onClick={() => setShowVenueModal(false)}><FiX /></button>
            </div>
            <div className="ca-modal-body">
              <div className="ca-form-grid">
                <div className="ca-field ca-form-grid-full">
                  <label className="ca-label">Venue Name *</label>
                  <input className="ca-input" value={venueForm.name} onChange={e => setVenueForm(f => ({ ...f, name: e.target.value }))} placeholder="e.g. Mandela National Stadium" />
                </div>
                <div className="ca-field ca-form-grid-full">
                  <label className="ca-label">Address</label>
                  <input className="ca-input" value={venueForm.address} onChange={e => setVenueForm(f => ({ ...f, address: e.target.value }))} placeholder="Full address" />
                </div>
                <div className="ca-field">
                  <label className="ca-label">Capacity</label>
                  <input className="ca-input" value={venueForm.capacity} onChange={e => setVenueForm(f => ({ ...f, capacity: e.target.value }))} placeholder="e.g. 45,000" />
                </div>
                <div className="ca-field">
                  <label className="ca-label">Type</label>
                  <select className="ca-select" value={venueForm.type} onChange={e => setVenueForm(f => ({ ...f, type: e.target.value as VenueType }))}>
                    <option>Home</option>
                    <option>Training</option>
                    <option>Alternative</option>
                  </select>
                </div>
                <div className="ca-field ca-form-grid-full">
                  <label className="ca-label">Facilities</label>
                  <input className="ca-input" value={venueForm.facilities} onChange={e => setVenueForm(f => ({ ...f, facilities: e.target.value }))} placeholder="e.g. Floodlights, VIP Lounge, Medical Bay" />
                </div>
              </div>
            </div>
            <div className="ca-modal-footer">
              <button type="button" className="ca-btn ca-btn-secondary" onClick={() => setShowVenueModal(false)}>Cancel</button>
              <button type="button" className="ca-btn ca-btn-primary" onClick={saveVenue}><FiPlus /> Add Venue</button>
            </div>
          </div>
        </div>
      )}

      <div className="ca-page-header">
        <div>
          <h1 className="ca-page-title">Club Profile &amp; Branding</h1>
          <p className="ca-page-subtitle">Manage club identity, brand assets, venues and media library.</p>
        </div>
        <div className="ca-page-actions">
          {activeTab === 'Profile' && dirty && (
            <button type="button" className="ca-btn ca-btn-secondary" onClick={discard}>Discard</button>
          )}
          {activeTab === 'Profile' && (
            <button type="button" className="ca-btn ca-btn-secondary" onClick={downloadGuidelines}>
              <FiDownload /> Download Guidelines
            </button>
          )}
          {activeTab === 'Profile' && (
            <button type="button" className="ca-btn ca-btn-primary" onClick={saveChanges} disabled={!dirty}
              style={{ opacity: dirty ? 1 : 0.5 }}>
              <FiSave /> Save Changes
            </button>
          )}
          {activeTab === 'Venues' && (
            <button type="button" className="ca-btn ca-btn-primary" onClick={openVenueModal}><FiPlus /> Add Venue</button>
          )}
          {activeTab === 'Media Assets' && (
            <button type="button" className="ca-btn ca-btn-primary" onClick={() => fileRef.current?.click()}><FiUpload /> Upload Asset</button>
          )}
          {form.clubName && (
            <a href="/clubs" className="ca-btn ca-btn-secondary" target="_blank" rel="noreferrer">
              <FiGlobe /> View Public Page
            </a>
          )}
        </div>
      </div>

      <div className="ca-tabs">
        {TABS.map(t => (
          <button key={t} type="button" className={`ca-tab${activeTab === t ? ' active' : ''}`} onClick={() => setActiveTab(t)}>{t}</button>
        ))}
      </div>

      {/* ── PROFILE TAB ── */}
      {activeTab === 'Profile' && (
        <div className="ca-content-grid">
          <div className="ca-content-main">
            <div className="ca-panel">
              <div className="ca-panel-header">
                <h2 className="ca-panel-title">General Club Information</h2>
                {dirty && <span style={{ fontSize: '0.72rem', color: '#f97316', fontWeight: 700 }}>Unsaved changes</span>}
              </div>
              <div className="ca-profile-form-grid">
                {FIELDS.map(({ label, key, type }) => (
                  <div key={key} className="ca-form-field">
                    <label className="ca-form-label">{label}</label>
                    <input className="ca-form-input" type={type || 'text'} value={form[key]} onChange={handleChange(key)} />
                  </div>
                ))}
                <div className="ca-form-field ca-form-field-full">
                  <label className="ca-form-label">Club Bio</label>
                  <textarea className="ca-form-input ca-form-textarea" rows={3} value={form.bio} onChange={handleChange('bio')} />
                </div>
              </div>
            </div>

            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Social &amp; Public Presence</h2></div>
              <div className="ca-profile-social-grid">
                {[
                  { icon: FiInstagram, platform: 'Instagram' },
                  { icon: FiTwitter,   platform: 'Twitter/X' },
                  { icon: FiYoutube,   platform: 'YouTube' },
                  { icon: FiLinkedin,  platform: 'LinkedIn' },
                  { icon: FiGlobe,     platform: 'Website', handle: form.website },
                ].map(({ icon: Icon, platform, handle }) => (
                  <div key={platform} className="ca-social-row">
                    <Icon className="ca-social-icon" />
                    <div className="ca-social-info">
                      <span className="ca-social-platform">{platform}</span>
                      <span className="ca-social-handle">{handle ?? '—'}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className="ca-content-aside">
            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Brand Guidelines</h2></div>
              <div className="ca-brand-preview-box">
                <div className="ca-brand-badge">{form.clubName ? form.clubName.slice(0, 2).toUpperCase() : '—'}</div>
                <span className="ca-brand-club-name">{form.clubName || 'Club Name'}</span>
              </div>
              <button type="button" className="ca-btn ca-btn-secondary" style={{ width: '100%', marginTop: 12 }} onClick={downloadGuidelines}>
                <FiDownload /> Download Guidelines
              </button>
            </div>

            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Brand Palette</h2></div>
              <div className="ca-palette-row">
                {PALETTE.map(color => (
                  <div key={color} className="ca-palette-swatch" style={{ background: color }} title={color} />
                ))}
              </div>
            </div>

            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Certification</h2></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {[
                  ['FUFA Licensed Club',  'Verified', 'green'],
                  ['CAF Member Club',     'Verified', 'green'],
                  ['League OS Verified',  'Verified', 'purple'],
                  ['Financial Compliance','Pending',  'orange'],
                ].map(([label, status, color]) => (
                  <div key={label} className="ca-cert-row">
                    <span className="ca-cert-label">{label}</span>
                    <span className={`ca-pill ca-pill-${color}`}>{status}</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Recent Branding Activity</h2></div>
              {RECENT_BRANDING.length === 0
                ? <p style={{ fontSize: '0.82rem', color: 'var(--color-text-muted)', margin: 0 }}>No branding activity yet.</p>
                : (
                  <div className="ca-activity-list">
                    {RECENT_BRANDING.map((r, i) => (
                      <div key={i} className="ca-activity-item">
                        <div className="ca-activity-dot" />
                        <div><p className="ca-activity-text">{r.text}</p><p className="ca-activity-time">{r.time}</p></div>
                      </div>
                    ))}
                  </div>
                )
              }
            </div>
          </div>
        </div>
      )}

      {/* ── VENUES TAB ── */}
      {activeTab === 'Venues' && (
        <div className="ca-content-grid">
          <div className="ca-content-main">
            <div className="ca-panel">
              <div className="ca-panel-header">
                <h2 className="ca-panel-title">Venue Directory</h2>
                <span className="ca-panel-count">{venues.length} venues</span>
              </div>
              <div className="ca-table-wrap">
                <table className="ca-table">
                  <thead><tr><th>Venue</th><th>Type</th><th>Capacity</th><th>Address</th><th>Facilities</th><th></th></tr></thead>
                  <tbody>
                    {venues.length === 0 && (
                      <tr><td colSpan={6} style={{ textAlign: 'center', color: 'var(--color-text-muted)', padding: '28px' }}>No venues yet. Add your home ground or training facility.</td></tr>
                    )}
                    {venues.map(v => (
                      <tr key={v.id}>
                        <td style={{ fontWeight: 700, color: 'var(--color-text-primary)' }}>{v.name}</td>
                        <td>
                          <span className={`ca-pill ${v.type === 'Home' ? 'ca-pill-purple' : v.type === 'Training' ? 'ca-pill-blue' : 'ca-pill-muted'}`}>
                            {v.type}
                          </span>
                        </td>
                        <td>{v.capacity || '—'}</td>
                        <td style={{ color: 'var(--color-text-secondary)', maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{v.address || '—'}</td>
                        <td style={{ color: 'var(--color-text-muted)', fontSize: '0.78rem', maxWidth: 140, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{v.facilities || '—'}</td>
                        <td>
                          <button type="button" className="ca-icon-btn" onClick={() => removeVenue(v.id)}><FiX /></button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div className="ca-content-aside">
            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Venue Types</h2></div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                {(['Home', 'Training', 'Alternative'] as VenueType[]).map(type => {
                  const count = venues.filter(v => v.type === type).length;
                  return (
                    <div key={type} style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: '1px solid var(--color-border)', fontSize: '0.8rem' }}>
                      <span style={{ color: 'var(--color-text-secondary)' }}>{type}</span>
                      <span style={{ fontWeight: 700, color: count > 0 ? 'var(--color-text-primary)' : 'var(--color-text-muted)' }}>{count}</span>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ── MEDIA ASSETS TAB ── */}
      {activeTab === 'Media Assets' && (
        <div className="ca-content-grid">
          <div className="ca-content-main">
            <input ref={fileRef} type="file" multiple style={{ display: 'none' }} onChange={e => handleFilePick(e.target.files)} />
            <div
              style={{ border: '2px dashed var(--color-border)', borderRadius: 10, padding: '28px 20px', textAlign: 'center', cursor: 'pointer', marginBottom: 16 }}
              onClick={() => fileRef.current?.click()}
              onDragOver={e => e.preventDefault()}
              onDrop={e => { e.preventDefault(); handleFilePick(e.dataTransfer.files); }}
            >
              <FiImage style={{ fontSize: '2rem', color: 'var(--color-text-muted)', display: 'block', margin: '0 auto 8px' }} />
              <p style={{ margin: '0 0 4px', fontSize: '0.85rem', fontWeight: 600, color: 'var(--color-text-secondary)' }}>Click to upload or drag &amp; drop</p>
              <p style={{ margin: 0, fontSize: '0.72rem', color: 'var(--color-text-muted)' }}>Logos, kits, banners, photos, videos · Max 50 MB</p>
            </div>

            <div className="ca-panel">
              <div className="ca-panel-header">
                <h2 className="ca-panel-title">Media Library</h2>
                <span className="ca-panel-count">{assets.length} assets</span>
              </div>
              <div className="ca-table-wrap">
                <table className="ca-table">
                  <thead><tr><th>File</th><th>Category</th><th>Size</th><th>Added</th><th></th></tr></thead>
                  <tbody>
                    {assets.length === 0 && (
                      <tr><td colSpan={5} style={{ textAlign: 'center', color: 'var(--color-text-muted)', padding: '28px' }}>No media assets yet. Upload your club crest, kits and other assets.</td></tr>
                    )}
                    {assets.map(a => (
                      <tr key={a.id}>
                        <td style={{ fontWeight: 600, color: 'var(--color-text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}>
                          <FiImage style={{ color: 'var(--color-text-muted)', flexShrink: 0 }} />{a.name}
                        </td>
                        <td><span className="ca-pill ca-pill-muted" style={{ fontSize: '0.62rem' }}>{a.category}</span></td>
                        <td style={{ color: 'var(--color-text-muted)' }}>{a.size}</td>
                        <td style={{ color: 'var(--color-text-muted)' }}>{a.addedAt}</td>
                        <td><button type="button" className="ca-icon-btn" onClick={() => removeAsset(a.id)}><FiTrash2 /></button></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div className="ca-content-aside">
            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">Asset Category</h2></div>
              <p style={{ fontSize: '0.78rem', color: 'var(--color-text-muted)', marginBottom: 8 }}>Select category before uploading</p>
              <select className="ca-select" value={mediaCategory} onChange={e => setMediaCategory(e.target.value)}>
                {MEDIA_CATEGORIES.map(c => <option key={c}>{c}</option>)}
              </select>
            </div>
            <div className="ca-panel">
              <div className="ca-panel-header"><h2 className="ca-panel-title">By Category</h2></div>
              {MEDIA_CATEGORIES.map(cat => {
                const count = assets.filter(a => a.category === cat).length;
                return (
                  <div key={cat} style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', borderBottom: '1px solid var(--color-border)', fontSize: '0.78rem' }}>
                    <span style={{ color: 'var(--color-text-secondary)' }}>{cat}</span>
                    <span style={{ fontWeight: 700, color: count > 0 ? 'var(--color-text-primary)' : 'var(--color-text-muted)' }}>{count}</span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </ClubAdminLayout>
  );
}
