import { useState } from 'react';
import { FiGlobe, FiInstagram, FiTwitter, FiYoutube, FiLinkedin, FiDownload, FiSave } from 'react-icons/fi';
import ClubAdminLayout from '../../../components/clubadmin/ClubAdminLayout';
import '../../../components/clubadmin/ClubAdminLayout.css';
import './ClubProfilePage.css';

const PALETTE = ['#FFD700', '#1A1A1A', '#7C3AED', '#FFFFFF', '#22C55E'];

const RECENT_BRANDING: { text: string; time: string }[] = [];

type FormData = {
  clubName: string; email: string; phone: string; website: string;
  founded: string; nickname: string; ground: string; colours: string; bio: string;
};

const INIT_FORM: FormData = {
  clubName: '',
  email: '',
  phone: '',
  website: '',
  founded: '',
  nickname: '',
  ground: '',
  colours: '',
  bio: '',
};

export default function ClubProfilePage() {
  const [form, setForm] = useState<FormData>(INIT_FORM);
  const [saved, setSaved] = useState<FormData>(INIT_FORM);
  const [toast, setToast] = useState('');
  const [dirty, setDirty] = useState(false);

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 3000); };

  const handleChange = (k: keyof FormData) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm(f => ({ ...f, [k]: e.target.value }));
    setDirty(true);
  };

  const saveChanges = () => {
    setSaved(form);
    setDirty(false);
    showToast('Club profile saved successfully');
  };

  const discard = () => {
    setForm(saved);
    setDirty(false);
    showToast('Changes discarded');
  };

  const downloadGuidelines = () => {
    const content = [
      `BRAND GUIDELINES — ${form.clubName}`,
      `Season 2025/26`,
      `Generated by League OS · ${new Date().toLocaleDateString()}`,
      ``,
      `CLUB IDENTITY`,
      `  Club Name:    ${form.clubName}`,
      `  Nickname:     ${form.nickname}`,
      `  Founded:      ${form.founded}`,
      `  Home Ground:  ${form.ground}`,
      `  Home Colours: ${form.colours}`,
      ``,
      `CONTACT & WEB`,
      `  Email:   ${form.email}`,
      `  Phone:   ${form.phone}`,
      `  Website: ${form.website}`,
      ``,
      `BRAND PALETTE`,
      `  ${PALETTE.join('  |  ')}`,
      ``,
      `CLUB BIO`,
      `  ${form.bio}`,
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = Object.assign(document.createElement('a'), {
      href: url,
      download: `${form.clubName.replace(/\s+/g, '_')}_brand_guidelines.txt`,
    });
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('Brand guidelines downloaded');
  };

  const FIELDS: { label: string; key: keyof FormData; type?: string }[] = [
    { label: 'Club Name', key: 'clubName' },
    { label: 'Official Email', key: 'email', type: 'email' },
    { label: 'Phone Number', key: 'phone', type: 'tel' },
    { label: 'Website', key: 'website' },
    { label: 'Founded', key: 'founded' },
    { label: 'Nickname', key: 'nickname' },
    { label: 'Home Ground', key: 'ground' },
    { label: 'Home Colours', key: 'colours' },
  ];

  return (
    <ClubAdminLayout>
      {toast && <div className="ca-toast">{toast}</div>}

      <div className="ca-page-header">
        <div>

          <h1 className="ca-page-title">Club Profile &amp; Branding</h1>
          <p className="ca-page-subtitle">Manage club identity, brand assets, descriptions and public-facing details.</p>
        </div>
        <div className="ca-page-actions">
          {dirty && (
            <button type="button" className="ca-btn ca-btn-secondary" onClick={discard}>Discard</button>
          )}
          <button type="button" className="ca-btn ca-btn-secondary" onClick={downloadGuidelines}>
            <FiDownload /> Download Guidelines
          </button>
          <button type="button" className="ca-btn ca-btn-primary" onClick={saveChanges} disabled={!dirty}
            style={{ opacity: dirty ? 1 : 0.5 }}>
            <FiSave /> Save Changes
          </button>
        </div>
      </div>

      <div className="ca-content-grid">
        <div className="ca-content-main">
          <div className="ca-panel">
            <div className="ca-panel-header">
              <h2 className="ca-panel-title">General Club Information</h2>
              {dirty && <span style={{ fontSize: '0.72rem', color: '#f97316', fontWeight: 700 }}>Unsaved changes</span>}
            </div>
            <div className="ca-profile-form-grid">
              {FIELDS.map(({ label, key, type }) => (
                <div key={key} className="ca-form-field">
                  <label className="ca-form-label">{label}</label>
                  <input
                    className="ca-form-input"
                    type={type || 'text'}
                    value={form[key]}
                    onChange={handleChange(key)}
                  />
                </div>
              ))}
              <div className="ca-form-field ca-form-field-full">
                <label className="ca-form-label">Club Bio</label>
                <textarea
                  className="ca-form-input ca-form-textarea"
                  rows={3}
                  value={form.bio}
                  onChange={handleChange('bio')}
                />
              </div>
            </div>
          </div>

          <div className="ca-panel">
            <div className="ca-panel-header"><h2 className="ca-panel-title">Social &amp; Public Presence</h2></div>
            <div className="ca-profile-social-grid">
              {[
                { icon: FiInstagram, platform: 'Instagram' },
                { icon: FiTwitter,   platform: 'Twitter/X' },
                { icon: FiYoutube,   platform: 'YouTube' },
                { icon: FiLinkedin,  platform: 'LinkedIn' },
                { icon: FiGlobe,     platform: 'Website', handle: form.website },
              ].map(({ icon: Icon, platform, handle }) => (
                <div key={platform} className="ca-social-row">
                  <Icon className="ca-social-icon" />
                  <div className="ca-social-info">
                    <span className="ca-social-platform">{platform}</span>
                    <span className="ca-social-handle">{handle ?? '—'}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="ca-content-aside">
          <div className="ca-panel">
            <div className="ca-panel-header"><h2 className="ca-panel-title">Brand Guidelines</h2></div>
            <div className="ca-brand-preview-box">
              <div className="ca-brand-badge">{form.clubName ? form.clubName.slice(0, 2).toUpperCase() : '—'}</div>
              <span className="ca-brand-club-name">{form.clubName || 'Club Name'}</span>
            </div>
            <button type="button" className="ca-btn ca-btn-secondary" style={{ width: '100%', marginTop: 12 }}
              onClick={downloadGuidelines}>
              <FiDownload /> Download Guidelines
            </button>
          </div>

          <div className="ca-panel">
            <div className="ca-panel-header"><h2 className="ca-panel-title">Brand Palette</h2></div>
            <div className="ca-palette-row">
              {PALETTE.map(color => (
                <div key={color} className="ca-palette-swatch" style={{ background: color }} title={color} />
              ))}
            </div>
          </div>

          <div className="ca-panel">
            <div className="ca-panel-header"><h2 className="ca-panel-title">Certification</h2></div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {[
                ['FUFA Licensed Club',  'Verified', 'green'],
                ['CAF Member Club',     'Verified', 'green'],
                ['League OS Verified',  'Verified', 'purple'],
                ['Financial Compliance','Pending',  'orange'],
              ].map(([label, status, color]) => (
                <div key={label} className="ca-cert-row">
                  <span className="ca-cert-label">{label}</span>
                  <span className={`ca-pill ca-pill-${color}`}>{status}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="ca-panel">
            <div className="ca-panel-header"><h2 className="ca-panel-title">Recent Branding Activity</h2></div>
            {RECENT_BRANDING.length === 0
              ? <p style={{ fontSize: '0.82rem', color: 'var(--color-text-muted)', margin: 0 }}>No branding activity yet.</p>
              : (
                <div className="ca-activity-list">
                  {RECENT_BRANDING.map((r, i) => (
                    <div key={i} className="ca-activity-item">
                      <div className="ca-activity-dot" />
                      <div>
                        <p className="ca-activity-text">{r.text}</p>
                        <p className="ca-activity-time">{r.time}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )
            }
          </div>
        </div>
      </div>
    </ClubAdminLayout>
  );
}
