import { render,screen,waitFor } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { describe,expect,it,vi,beforeEach } from 'vitest';
import CompetitionDetail from './sections/CompetitionDetail'; import Leagues from './sections/Leagues'; import MyTeam from './sections/MyTeam'; import * as service from '../../../services/fantasyService';
import { competitionFromApi } from './data';
import type { FantasyCompetition } from '../../../services/fantasyService';
vi.mock('../../../services/fantasyService',async()=>{const actual=await vi.importActual('../../../services/fantasyService');return {...actual,fetchMyLeagues:vi.fn(),fetchPublicLeagues:vi.fn(),fetchCompetitionLeaderboard:vi.fn(),fetchLeagueMembers:vi.fn(),fetchLeagueStandings:vi.fn()};});
const api={id:'c1',sport:'football',name:'UPL Fantasy',description:'Rules',season:'s1',season_name:'2026/27',enabled:true,registration_state:'OPEN',visibility:'PUBLIC',squad_size:1,starting_lineup_size:1,bench_size:0,initial_budget:'100',max_players_per_team:3,captain_multiplier:'2',vice_captain_fallback:true,free_transfers_per_gameweek:1,transfer_penalty:4,position_rules:{GK:1},formation_rules:{GK:{min:1,max:1}},tie_break_rules:[],gameweek_rules:{},registration_deadline:null,prize_metadata:{},scoring_rules:[],competition:'real',current_gameweek:{id:'g1',fantasy_competition:'c1',number:1,name:'GW1',starts_at:'',deadline_at:'',ends_at:'',status:'OPEN',fixtures:[],fixture_details:[]},entries:0,total_gameweeks:1} as const;
const competition=competitionFromApi(api as unknown as FantasyCompetition);
const team={id:'t1',competitionId:'c1',teamName:'My XI',managerName:'Me',budgetRemaining:10,squad:[{playerId:'p1',isStarter:true}],captainId:'p1',viceCaptainId:null,freeTransfers:1,totalPoints:0,gwPoints:0,overallRank:null,submitted:true,score:{breakdown:{players:[{player_id:'p1',player_name:'Keeper',position:'GK',base_points:'0',correction_points:'0',captain_bonus:'0',final_points:'0',statistics_available:false,captain:true}]}}} as never;
beforeEach(()=>{vi.clearAllMocks();vi.mocked(service.fetchPublicLeagues).mockResolvedValue([]);vi.mocked(service.fetchCompetitionLeaderboard).mockResolvedValue([]);vi.mocked(service.fetchLeagueMembers).mockResolvedValue([]);vi.mocked(service.fetchLeagueStandings).mockResolvedValue([]);});
describe('latest Fantasy sections',()=>{
 it('shows the season name without using the canonical UUID as its label',()=>{render(<CompetitionDetail competition={competition} hasTeam={false} onBack={()=>{}} onCreateTeam={()=>{}} onManageTeam={()=>{}}/>);expect(screen.getByText('Season 2026/27')).toBeInTheDocument();expect(screen.queryByText('Season s1')).not.toBeInTheDocument();});
 it('loads members and standings for the selected league',async()=>{vi.mocked(service.fetchMyLeagues).mockResolvedValue([{id:'l1',name:'First',fantasy_competition:'c1',visibility:'PUBLIC',description:'',capacity:null,member_count:1},{id:'l2',name:'Selected',fantasy_competition:'c1',visibility:'PUBLIC',description:'',capacity:null,member_count:2}]);render(<Leagues competition={competition} team={team}/>);await userEvent.click(await screen.findByText('Selected'));await waitFor(()=>expect(service.fetchLeagueMembers).toHaveBeenCalledWith('l2'));expect(service.fetchLeagueStandings).toHaveBeenCalledWith('l2');});
 it('shows Awaiting statistics instead of invented player points',()=>{render(<MyTeam competition={competition} team={team} players={[{id:'p1',name:'Keeper',club:'Club',clubShort:'CLB',clubColor:'#000',sport:'football',position:'GK',positionLabel:'Goalkeeper',price:5,form:0,totalPoints:0,gwPoints:0,ownership:0,status:'ready'}]} onGoTransfers={()=>{}} onSwapLineup={()=>{}}/>);expect(screen.getAllByText('Awaiting statistics').length).toBeGreaterThan(0);});
});
